Python triggers on alphanumeric
kiteco/vscode-plugin pull request #328
Opened 2020-09-29 20:06 UTC by tonycheang

Addresses Python case for https://github.com/kiteco/kiteco/issues/11317

### What was done
- Allows placeholders to request completions for Python only
- Side effect: suppresses native completions on these characters for Python

2020-09-29 20:57 UTC, its-dhung requested changes

2020-09-29 20:57 UTC, its-dhung commented on src/kite.js
> +      '1', '2', '3', '4', '5', '6', '7', '8', '9', '0'
Let's leave out numbers for now since we don't suggest number literals. We can add this back in when lexical models can suggest number constants.

2020-09-29 21:55 UTC, its-dhung approved these changes

2020-09-30 17:01 UTC, tonycheang commented
@its-dhung I don't use tab to select completions normally, but the jrieken from vscode pointed out that tab in this case could potentially be confusing. It prefers selecting the completion over moving to the next tab stop, but it does do both. The user can also manually opt in for completions within snippets by setting `editor.suggest.snippetsPreventQuickQuickSuggestion` to `false`. Should we still make this change?

2020-09-30 17:29 UTC, metalogical commented
(https://github.com/microsoft/vscode/issues/107742#issuecomment-701181250)

@its-dhung : I agree that we should probably not merge this change. If anything, we should suggest to the user that they may want to change this setting (`editor.suggest.snippetsPreventQuickSuggestions`) to enable autotrigger within snippets.

@tonycheang the response there doesn't explain why it magically gets fixed by adding the alphabet to the trigger char set. It seems like "correct" behavior in VS Code would disable autocompletions entirely, ignoring the extension's trigger char set entirely. It may be worth pointing this out in a quick comment on that issue.

2020-10-02 02:14 UTC, closed without merging